generationBoomerang/src/Entity/Articles.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\ArticlesRepository;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\HttpFoundation\File\File;
use Doctrine\Common\Collections\ArrayCollection;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;


/**
 * @ORM\Entity(repositoryClass=ArticlesRepository::class)
 * @ORM\HasLifecycleCallbacks
 * @Vich\Uploadable()
 * @UniqueEntity(
 * fields={"titreArticle"},
 * message="un autre article possède déjà ce titre, merci de le modifier"
 * ) 

 */
class Articles
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;
    

    /**
     * @ORM\Column(type="string", length=50)
     * 
     *
     */
    private $titreArticle;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min=50, minMessage="Le contenu de l'article doit faire plus de 50 caratères", allowEmptyString=false)
     *
     */
    private $ContenuArticle;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="string", length=255)
     */
     
    private $slug;

   
    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $video;

    
    /**
     * Undocumented variable
     * @ORM\OneToMany(targetEntity=Commentaires::class, mappedBy="Article", orphanRemoval=true)
     *
     */
 
    private $commentaires;

    /**
     * @ORM\Column(type="datetime",nullable=true)
     */
    private $UpdatedAt;

    /**
     * @ORM\OneToMany(targetEntity=Liker::class, mappedBy="article", orphanRemoval=true)
     */
    private $likers;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="articles")
     * @ORM\JoinColumn(nullable=true)
     */
    private $author;

    /**
     * @ORM\OneToMany(targetEntity=Image::class, mappedBy="article", orphanRemoval=true,cascade={"persist"})
     * @Assert\Valid()
     */
    private $images;

    /**
     * @ORM\Column(type="string", length=50)
     * 
     */
    private $accroche;

    /**
     * @ORM\Column(type="text", length=700)
     */
    private $intro;

    /**
     * @ORM\ManyToOne(targetEntity=Pole::class, inversedBy="articles")
     * @ORM\JoinColumn(nullable=true)
     */
    private $pole;

    public function __construct()
    {
        $this->commentaires = new ArrayCollection();
        $this->likers = new ArrayCollection();
        $this->images = new ArrayCollection();
    }

    /**
     * permet d'initialiser le slug
     * @ORM\PrePersist
     * @ORM\PreUpdate
     * 
     * @return  void
     */
    public function initializeSlug(){
        if(empty($this->slug)) {
            $slugify = new Slugify();
            $this->slug =$slugify->slugify($this->titreArticle);
        }
    }
    
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitreArticle(): ?string
    {
        return $this->titreArticle;
    }

    public function setTitreArticle(string $titreArticle): self
    {
        $this->titreArticle = $titreArticle;

        return $this;
    }

    public function getContenuArticle(): ?string
    {
        return $this->ContenuArticle;
    }

    public function setContenuArticle(string $ContenuArticle): self
    {
        $this->ContenuArticle = $ContenuArticle;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getVideo(): ?string
    {
        return $this->video;
    }

    public function setVideo(?string $video): self
    {
        $this->video = $video;

        return $this;
    }

    /**
     * @return Collection|Commentaires[]
     */
    public function getCommentaires(): Collection
    {
        return $this->commentaires;
    }

    public function addCommentaire(Commentaires $commentaire): self
    {
        if (!$this->commentaires->contains($commentaire)) {
            $this->commentaires[] = $commentaire;
            $commentaire->setArticle($this);
        }

        return $this;
    }

    public function removeCommentaire(Commentaires $commentaire): self
    {
        if ($this->commentaires->contains($commentaire)) {
            $this->commentaires->removeElement($commentaire);
            // set the owning side to null (unless already changed)
            if ($commentaire->getArticle() === $this) {
                $commentaire->setArticle(null);
            }
        }

        return $this;
    }


    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->UpdatedAt;
    }

    public function setUpdatedAt(\DateTimeInterface $UpdatedAt): self
    {
        $this->UpdatedAt = $UpdatedAt;

        return $this;
    }

    /**
     * @return Collection|Liker[]
     */
    public function getLikers(): Collection
    {
        return $this->likers;
    }

    public function addLiker(Liker $liker): self
    {
        if (!$this->likers->contains($liker)) {
            $this->likers[] = $liker;
            $liker->setArticle($this);
        }

        return $this;
    }

    public function removeLiker(Liker $liker): self
    {
        if ($this->likers->contains($liker)) {
            $this->likers->removeElement($liker);
            // set the owning side to null (unless already changed)
            if ($liker->getArticle() === $this) {
                $liker->setArticle(null);
            }
        }

        return $this;
    }

      /**
     *
     * @param User $user
     * @return boolean
     */
    public function isLikedByUser(User $user) : bool {
        foreach($this->likers as $like) {
            if($like->getUser() === $user) return true;
        }

        return false;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    /**
     * @return Collection|Image[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setArticle($this);
        }

        return $this;
    }

    public function removeImage(Image $image): self
    {
        if ($this->images->contains($image)) {
            $this->images->removeElement($image);
            // set the owning side to null (unless already changed)
            if ($image->getArticle() === $this) {
                $image->setArticle(null);
            }
        }

        return $this;
    }

    public function getAccroche(): ?string
    {
        return $this->accroche;
    }

    public function setAccroche(?string $accroche): self
    {
        $this->accroche = $accroche;

        return $this;
    }

    public function getIntro(): ?string
    {
        return $this->intro;
    }

    public function setIntro(string $intro): self
    {
        $this->intro = $intro;

        return $this;
    }

    public function getPole(): ?Pole
    {
        return $this->pole;
    }

    public function setPole(?Pole $pole): self
    {
        $this->pole = $pole;

        return $this;
    }
}

generationBoomerang/src/Controller/ArticlesController.php
<?php

namespace App\Controller;

use App\Entity\Pole;
use App\Entity\Image;
use App\Entity\Liker;
use App\Entity\Articles;
use App\Form\ArticlesType;
use Cocur\Slugify\Slugify;
use App\Entity\Commentaires;
use App\Form\CommentairesType;
use App\Repository\LikerRepository;
use Symfony\Component\Mercure\Update;
use App\Repository\ArticlesRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Messenger\MessageBusInterface;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Validator\Constraints\NotNull;


class ArticlesController extends AbstractController
{
    

    /**
     * @Route("/poles/publications", name="articles_pole_index", methods={"GET", "POST"})
     * @Route("/publications", name="articles_publications_index", methods={"GET", "POST"})
     */
    public function publications(ArticlesRepository $articlesRepository, Request $request, PaginatorInterface $paginator): Response
    {
        
        $currentRoute = $request->attributes->get('_route');
        if ( $currentRoute == 'articles_publications_index'){
            $donnees = $this->getDoctrine()->getRepository(Articles::class)->findBy(['pole'=>null],['createdAt' => 'desc']);
        }else{
            $donnees = $articlesRepository->searchPoleNotNull();
        }
        
        $sort = 'desc';
        $option1 ="Articles les plus récents";
        $option2 = "Articles les plus anciens";  

        if ($request->getMethod() == "POST")
        { 
            $keyWord = $request->request->get('keyWord');
            $donnees = $articlesRepository->search($keyWord);  
            if ($donnees == null) {
                $this->addFlash('erreur', 'Aucun article contenant ce mot clé dans le titre n\'a été trouvé, essayez en un autre.');

            }
        }

        $articles = $paginator->paginate($donnees, $request->query->getInt('page', 1), 8 );

        if(isset($_GET['sort'])){
            if($_GET['sort'] == 'Articles les plus anciens'){
            $sort = 'asc';
            $option1 ="Articles les plus anciens";
            $option2 = "Articles les plus récents";
            }else{
                $sort = 'desc';
                $option1 ="Articles les plus récents";
                $option2 = "Articles les plus anciens";
            }
        }

        if(isset($_GET['inno'])){
            
        }

            return $this->render('articles/index.html.twig', [
                'articles' => $articles,
                'sort' => $sort,
                'option1' => $option1,
                'option2' => $option2

        ]);
    }


    /**
     * @Route("pole/nouvelle-publication", name="articles_pole_new", methods={"GET","POST"})
     * @Route("publications/nouvelle-publication", name="articles_publications_new", methods={"GET","POST"})
     * @Security("is_granted('ROLE_ADMIN') or is_granted('ROLE_FONDATEUR') or is_granted('ROLE_ABONNE')")
     */
    public function new(Request $request, EntityManagerInterface $manager): Response
    {
        $article = new Articles();
        
        $currentRoute = $request->attributes->get('_route');
        if ( $currentRoute == 'articles_pole_new'){
            $poles = $this->getDoctrine()->getRepository(Pole::class)->findBy([
                'responsable' => $this->getUser()
            ]);
        }
        

        $form = $this->createForm(ArticlesType::class, $article);
        $form->handleRequest($request);
        

        if ($form->isSubmitted() && $form->isValid()) {
            

            if ( $currentRoute == 'articles_pole_new'){
                if ($request->request->get('pole') != NULL){
                    $pole=$this->getDoctrine()->getRepository(Pole::class)->find($request->request->get('pole'));            
                $article->setPole($pole);
                }
                
            }
            
           
            
            $images = $form->get("images")->getData();
            foreach( $images as $image){
                $img = new Image();
                $img->setImageFile($image);
                $article->addImage($img);
            }

            $article->setCreatedAt(new \DateTime('now'));
            $article->setAuthor($this->getUser());

            
            $entityManager = $this->getDoctrine()->getManager();
            

            $entityManager->persist($article);
            if($request->request->get('action') !== null){
                return $this->render('articles/preview.html.twig', [
                    'images' => $images,
                    'article' => $article,
                ]);
            }

            $entityManager->flush();

        if ( $currentRoute == 'articles_pole_new'){  
            return $this->redirectToRoute('articles_pole_show',[
                'slug' => $article->getSlug()
            ]);

        }else{ 
            return $this->redirectToRoute('articles_publications_show',[
                'slug' => $article->getSlug()
            ]);
         }   

        }

        if ( $currentRoute == 'articles_pole_new'){ 
                               
            return $this->render('articles/new.html.twig', [
                'poles' => $poles,
                'article' => $article,
                'form' => $form->createView(),
            ]);
        }else{             
            return $this->render('articles/new.html.twig', [
                'article' => $article,
                'form' => $form->createView(),
        ]);}
       
    }

    /**
    * @Route("pole/{slug}", name="articles_pole_show")    * 
    * @Route("publications/{slug}", name="articles_publications_show")
    * 
    */
    public function article($slug, Request $request)
    {
        
        $article = $this->getDoctrine()->getRepository(Articles::class)->findOneBy(['slug' => $slug]);

        $commentaires = $this->getDoctrine()->getRepository(Commentaires::class)->findBy([
            'Article' => $article,
            'actif' => 1
        ],['createdAt' => 'desc']);

        if(!$article)
        {
            throw $this->createNotFoundException('L\'article n\'existe pas');
        }

        $commentaire = new Commentaires();

        $form = $this->createForm(CommentairesType::class, $commentaire);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) 
        {
            $commentaire->setArticle($article)
                        ->setCreatedAt(new \DateTime('now'))
                        ->setUser($this->getUser())
                        ->setActif(true)
                        ->setRgpd(true);
            $doctrine = $this->getDoctrine()->getManager();
            $doctrine->persist($commentaire);
            $doctrine->flush();

            $currentRoute = $request->attributes->get('_route');
            if ( $currentRoute == 'articles_pole_show'){
                return $this->redirectToRoute('articles_pole_show',[
                    'slug' => $article->getSlug()
                ]);
            }else{
                return $this->redirectToRoute('articles_publications_show',[
                    'slug' => $article->getSlug()
                ]);
            }
            

        }

        return $this->render('articles/show.html.twig', [
            'form' => $form->createView(),
            'article' => $article,
            'commentaires' => $commentaires,
        ]);
    }

    /**
     * @Route("pole/{slug}/edit", name="articles_pole_edit", methods={"GET","POST"})
     * @Route("publications/{slug}/edit", name="articles_publications_edit", methods={"GET","POST"})
     * @Security("is_granted('ROLE_USER') and user  === article.getAuthor() or is_granted('ROLE_ADMIN')", message="Cette annonce ne vous appartient pas, vous ne pouvez pas la modifier")
     * @param Articles $article
     * @return Response
     */
    public function edit(Request $request, Articles $article): Response
    {
        $poles = $this->getDoctrine()->getRepository(Pole::class)->findAll();
        $form = $this->createForm(ArticlesType::class, $article);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $currentRoute = $request->attributes->get('_route');
            if ( $currentRoute == 'articles_pole_new'){
                $pole=$this->getDoctrine()->getRepository(Pole::class)->find($request->request->get('pole'));            
                $article->setPole($pole);
            }
            

            foreach($form->get("images")->getData() as $image){
                $img = new Image();
                $img->setImageFile($image);
                $article->addImage($img);
            }

            $slugify = new Slugify();
            $article->setSlug($slugify->slugify($article->getTitreArticle()));

            $this->getDoctrine()->getManager()->flush();

            $currentRoute = $request->attributes->get('_route');
            if ( $currentRoute == 'articles_pole_edit'){
                return $this->redirectToRoute('articles_pole_show',[
                    'slug' => $article->getSlug()
                ]);
                
            }else{
                return $this->redirectToRoute('articles_publications_show',[
                    'slug' => $article->getSlug()
                ]);
                
            }
            
        }

        return $this->render('articles/edit.html.twig', [
            'poles' => $poles,
            'article' => $article,
            'form' => $form->createView(),
        ]);
    }

    /**
     * permet de supprimer

generationBoomerang/templates/articles/_collection.html.twig
 {% block articles_images_widget %}
    <p>vous pouvez ajouter vos propres images</p>
    {{form_widget(form)}}

    <div class="form-group">
        <button form="button" id="add-image" class="btn btn-primary">ajouter une image</button>
    </div>
{% endblock %}

{% block articles_images_entry_row %}
    {{ form_widget(form)}}
{% endblock %}

{% block articles_images_entry_widget %}
    <div class="form-group" id="block_{{id}}" >
        <div class="row">
            <div class="col-10">
                <div class="row">
                    <div class="col">
                        {{ form_widget(form.filename)}}
                    </div>
                </div>
            </div>
            <div class="col-2">
                <button type="button" data-action="delete" data-target="#block_{{id}}" class="btn btn-danger">X</button>
            </div> 
        </div>
    </div>
{% endblock %}

generationBoomerang/templates/articles/_delete_form.html.twig
<form method="post" action="{{ path('articles_delete', {'slug': article.slug}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ article.slug) }}">
    <button class="btn btn-danger">Suppression</button>
</form>

generationBoomerang/templates/articles/_form.html.twig
<div class="form-group md-6 offset-3">
    
    {{ form_start(form) }} 
    
        {{form_row(form.titreArticle, {'label':'le titre de l\'article','attr': {'placeholder': 'titre article', 'class':"form-control"}})}}
    <div class="my-3">
        {{form_row(form.contenuArticle, {'label':'le contenu de l\'article','attr': {'placeholder': 'contenu article', 'rows': '15', 'class':"form-control"}})}}
    </div> 
       
    <div class="my-3">
        {{form_row(form.video, {'label':'l\' url de la video ','attr': {'placeholder': 'Video', 'class':"form-control"}})}}
    </div>
    {# <div class="my-3">
        {{form_row(form.images.imageFile, {'label':'Vos images','attr': {'placeholder': 'Image', 'class':"form-control"}})}}
    </div> #}

    <div class="my-3">
        <button type="submit" class="btn btn-success">{{ button_label|default('créer') }}</button>
        <a href="{{ path('articles_index') }}" class="btn btn-primary mx-3">Retour à la liste</a>  
    </div>
    
</div>

    {{ form_end(form) }}


    

generationBoomerang/templates/articles/adminIndex.html.twig
{% extends 'base.html.twig' %}

{% block title %}Articles index{% endblock %}

{% block body %}
    <h1>Articles index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>TitreArticle</th>
                <th>ContenuArticle</th>
                <th>CreatedAt</th>
                <th>Slug</th>
                <th>Image</th>
                <th>Video</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for article in articles %}
            <tr>
                <td>{{ article.id }}</td>
                <td>{{ article.titreArticle }}</td>
                <td>{{ article.ContenuArticle }}</td>
                <td>{{ article.createdAt ? article.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ article.slug }}</td>
                <td>{{ article.Image }}</td>
                <td>{{ article.video }}</td>
                {# <td>
                    <a href="{{ path('articles_show', {'id': article.id}) }}">show</a>
                    <a href="{{ path('articles_edit', {'id': article.id}) }}">edit</a>
                </td> #}
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('articles_new') }}">Create new</a>
{% endblock %}

generationBoomerang/templates/articles/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% endblock %}

{% block body %}
<h1 class="text-center my-3">Modification de l'article</h1>
    <div class="container backgroundContainerNewPub pt-5">
        <div class="d-flex">
            <img src="{{ asset('/img/logoGBnoir.png') }}" alt="generationBoomerang logo" class="logoHeader pt-1 pb-3 mx-auto">
        </div>
                       
                {{  form_start(form, {'attr': {'class':'px-5'}}) }} 
                    <hr>
                {% if pole is defined %}
                    <div class="form-group">
                        <select name="pole" id="pole" class="form-control col-3" required>
                                <option value="">Choisissez le pôle</option>
                            {% for pole in poles %}
                                <option value="{{pole.id}}">{{pole.nomPole}}</option>
                            {% endfor %}
                        </select>
                    </div>
                {% endif %}>
                        {# Ajout du titre  #}
                <div class="form-group mb-4">
                    <div style="font-weight:bold;">{{form_label(form.titreArticle,'Titre de la publication')}}</div>                 
                    {{form_widget(form.titreArticle, {'attr': {'class': 'col-4 form-control'}})}}
                    <small class="" style="font-style: italic;">( 50 caractères maximum )</small>
                </div>

{# Ajout de l'accroche  #}
                <div class="form-group mb-4">
                    <div style="font-weight:bold;">{{form_label(form.accroche,'Phrase d\'accroche')}} </div>                      
                    {{form_widget(form.accroche, {'attr': {'class': 'col-4 form-control'}})}}
                    <small style="font-style: italic;">( 100 caractères maximum )</small>
                </div>

{# Ajout de l'intro  #}
                <div class="form-group mb-4">
                    <div style="font-weight:bold;">{{form_label(form.intro,'Introduction de la publication ( visible par tous )')}}</div>                       
                    {{form_widget(form.intro, {'attr': {'rows': '5', 'class':'col-10 form-control'}})}}
                    <small style="font-style: italic;">( 2000 caractères maximum )</small>
                    <div id="demo" class="collapse" style="color:red;font-style:italic">L'introduction de la publication est obligatoire</div>
                </div>

{# Ajout de la contenu  #}
                <div class="form-group mb-4">
                    <div style="font-weight:bold;">{{form_label(form.contenuArticle,'Contenu de la publication ( visible uniquement par les membres )')}}</div>                      
                    {{form_widget(form.contenuArticle, {'attr': {'rows': '5', 'class':'col-10 form-control'}})}}
                    <small style="font-style: italic;">( 3600 caractères maximum )</small>
                    <div id="demo2" class="collapse" style="color:red;font-style:italic">Le contenu de la publication est obligatoire</div>
                </div>

 {# Affichage des images #}
                <div class="row">
                {% for image in article.images %}
                    
                        <div class="col-2" id={{image.id}}>
                            <img src="{{ vich_uploader_asset(image, 'imageFile')}}" class="img-thumbnail" alt="Cinque Terre" width="304px" height="236px"> 
                            <a href="{{ path('image_remove', {'id' : image.id})}}" type="button" class="close" >&times;</a>
                        </div>
                    
                {% endfor %}
                </div>

 {# Ajout des photos  #}
                <div class="form-group mb-4 d-flex flex-column">
                   <div style="font-weight:bold;">{{form_label(form.images,'Photos de la publication')}}</div>  
                    
                              <div id="preview2" class="p-2"></div>
                                
                    <small style="font-style: italic;">( jusque 5 photos au format .jpg, .jpeg, .png (poids maximum 10mo / photo) )</small>
                    <div class="d-flex inputFormArticle" onchange="previewFiles()">{{form_widget(form.images, {'attr': {'id':'browse','class': 'col-4 form-control p-0'}})}}</div>
                    <div id="items">                       
                    </div>                    
                </div>

                
{# Ajout de la videos  #}
                <div class="form-group mb-4">
                    <div style="font-weight:bold;">{{form_label(form.video,'Video de la publication')}}</div>  
                    <small style="font-style: italic; color:red;">( Lien Youtube uniquement durée 15 minutes, vidéo non obligatoire )</small>
                    {{form_widget(form.video, {'attr' : {'placeholder':'Copiez ici le lien de votre vidéo','class':'col-6 form-control'}})}}
                </div>
                        <div class="checkbox">
                            <label><input type="checkbox" value="" required> En rédigeant cette publication, vous acceptez <a href="" style="color:rgb(244,69,6)">les termes et conditions</a> la concernant</label>
                        </div>
                        <div class="my-3 buttonCreatePub">
                            <button type="submit" class="btn ">{{ button_label|default('Mise à jour') }}</button>                            
                        {% if pole is defined %}
                            <a href="{{ path('articles_pole_index') }}" class="btn btn-primary ml-auto">Retour à la liste</a>  
                        {% else %}
                            <a href="{{ path('articles_publications_index') }}" class="btn btn-primary ml-auto">Retour à la liste</a>  
                        {% endif %}
                        </div>
                {{ form_end(form) }} 
                                           
           
    </div>
{% endblock %}

{% block _articles_images_widget %}
    <p>vous pouvez ajouter vos propres images</p>
    {{form_widget(form)}}

    <div class="form-group">
        <button form="button" id="add-image" class="btn btn-primary">ajouter une image</button>
    </div>
{% endblock %}

{% block _articles_images_entry_row %}
    {{ form_widget(form)}}
{% endblock %}

{% block _articles_images_entry_widget %}
    <div class="form-group" id="block_{{id}}" >
        <div class="row">
            <div class="col-10">
                <div class="row">
                    <div class="col">
                        {{ form_widget(form.image)}}
                    </div>
                </div>
            </div>
            <div class="col-2">
                <button type="button" data-action="delete" data-target="#block_{{id}}" class="btn btn-danger">X</button>
            </div> 
        </div>
    </div>
{% endblock %}

{% block javascripts %} 
    
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <script>
        function onClickImgRemove(event){
            event.preventDefault();

            const url = this.href;

            axios.get(url).then(function(response){
                var id = response.data.id
                document.getElementById(id).remove()
            }).catch(function(error){
                
            });
        }
        document.querySelectorAll('a.close').forEach(function(link){
            link.addEventListener('click', onClickImgRemove);
        });

          function handleDeleteButtons(){
            $('button[data-action="delete"]').click(function(){
                const target= this.dataset.target;
                console.log(target);
                $(target).remove();
            })
        }
        handleDeleteButtons();

     $(document).ready(function(){  
            var i=1;  
        $('#add').click(function(){  
           
           if (i<5){
           $('#items').append('<div class="d-flex inputFormArticle inputAdded" id="removeDiv'+i+'"><input type="file" id="articles_images" multiple="multiple" name="articles[images][]" class="form-control mt-1" style="width:40%;"></input><button type="btn btn-danger" class="buttonRemove ml-1 mt-1" id="'+i+'" style="background-color:rgb(255,34,39);color:white;width:3em;border-radius:10px;">-</button></div>')
           i++;  
           }else{
               print('Seulement 5 photos');
           }
         });  

        $(document).on('click', '.buttonRemove', function(){  
           var button_id = $(this).attr("id");   
           $('#removeDiv'+button_id+'').remove();
           i--; 
        });  

        $(document).on('click', '.resetButton', function(){             
           $('.inputAdded').remove();  
           i=1;
        });
     })

     
// Fonction multi upload image //
function previewFiles() {

  var preview = document.querySelector('#preview2');
  var files   = document.querySelector('input[type=file]').files;

  function readAndPreview(file) {

    
    if ( /\.(jpe?g|png|gif)$/i.test(file.name) ) {
      var reader = new FileReader();

      reader.addEventListener("load", function () {
        var image = new Image();
        image.height = 100;
        image.title = file.name;
        image.src = this.result;
        image.style.padding = "0.3em";
        preview.appendChild( image );
      }, false);

      reader.readAsDataURL(file);
    }

  }

  if (files) {
    [].forEach.call(files, readAndPreview);
  }

}
    </script>
{% endblock %}